### ISSUE TITLE
provide better handling of missing namespaces during recovery

### ISSUE THREAD

**Issue by davelarsen58** [davelarsen58/pmemtool#12]
This particular traceback was obtained during a recovery operation where a new region was created, however the namespace had not yet been created.

Traceback (most recent call last):
  File "./recovery.py", line 356, in <module>
    main()
  File "./recovery.py", line 351, in main
    status = recover_all()
  File "./recovery.py", line 274, in recover_all
    data['ns_name']     =  ''.join(n.get_ns_dev(socket_num))
  File "/homes/dplarsen/src/pmemtool/ndctl.py", line 122, in get_ns_dev
    tmp  =  json.load(f)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by davelarsen58** [comment]
The workaround for this issue is to manually create the namespace on the newly created region.
Example:
  sudo ndctl create-namespace -r region0

**Comment by davelarsen58** [comment]
See workaround
