### ISSUE TITLE
pmt --timers throws error when --timers option provided

### ISSUE THREAD

**Issue by davelarsen58** [davelarsen58/pmemtool#13]
------------Start Recovery function timers---------------
                      Function  Elapsed       Start         End
------------------------------ --------- ----------- ------------
Traceback (most recent call last):
  File "./pmt", line 322, in <module>
    main(sys.argv[1:])
  File "./pmt", line 317, in main
    r.print_timers()
  File "/homes/dplarsen/src/pmemtool/recovery.py", line 422, in print_timers
    first = t[0]['tic']
IndexError: list index out of range

**Comment by davelarsen58** [comment]
Error was caused by calling print_timers() in recovery.py module when there was no profile data for recovery.
Fixed by adding a trace entry in the print_timers() function so there would always be one entry.

**Comment by davelarsen58** [comment]
Fixed in pmemtool v1.02.1

**Comment by davelarsen58** [comment]
Fixed in pmemtool v1.02.1
