### ISSUE TITLE
PMT Namespace error while testing recovery

### ISSUE THREAD

**Issue by tkremer2005** [davelarsen58/pmemtool#2]
<hostname>:~ # pmt
Traceback (most recent call last):
  File "./pmt", line 188, in <module>
    main(sys.argv[1:])
  File "./pmt", line 141, in main
    nsDevList = n.get_ns_device_list_by_dimm(dimm)
  File "/usr/share/pmemtool-main/ndctl.py", line 272, in get_ns_device_list_by_dimm
    ns_device_list = get_region_ns_device_list(region)
  File "/usr/share/pmemtool-main/ndctl.py", line 129, in get_region_ns_device_list
    for d in range(len(ndctl['regions'][r]['namespaces'])):
KeyError: 'namespaces'
<hostname>:~ #

**Comment by davelarsen58** [comment]
Added functionality to https://github.com/davelarsen58/pmemtool/tree/issue03

**Comment by davelarsen58** [comment]
Functionality integrated into release 0.90
https://github.com/davelarsen58/pmemtool/releases/tag/0.90

**Comment by tkremer2005** [comment]
Hi David,

we get an new error message from teh latest 1.00 release:

*r1ldassps4005:/usr/share/pmemtool-main #* pmt

Traceback (most recent call last):

  File "./pmt", line 239, in <module>

    main(sys.argv[1:])

  File "./pmt", line 142, in main

    i.dimms = i.parse_dimm()

  File "/usr/share/pmemtool-main/ipmctl.py", line 233, in parse_dimm

    if white_list[root[dimm][dimm_attr].tag] == 1:

KeyError: 'FWActiveAPIVersion'

I put an new issue on github for your information...

thanks
Thomas
